### ISSUE TITLE
Uraih - DSI 6 - Deloitte Resume Draft

### ISSUE THREAD

**Issue by DataChoo2018** [ga-dc-outcomes/deloitteresume#1]
I have attached a draft resume for the Deloitte recruiting event.

**Comment by DataChoo2018** [comment]
[Resume_Uraih 2017 II.docx](https://github.com/ga-dc-outcomes/deloitteresume/files/1419637/Resume_Uraih.2017.II.docx)

**Comment by CoachJoyhaugen** [comment]
Hi!  I am going to encourage you to go back and read through the Resume Section.  Follow the rec format, add your GA experience, etc.  Once you have done that you, please re-submit.
