### ISSUE TITLE
Kyle Santana Resume

### ISSUE THREAD

**Issue by ksantana3** [ga-dc-outcomes/deloitteresume#10]
[Kyle_Santana_Resume.pdf](https://github.com/ga-dc-outcomes/deloitteresume/files/1423030/Kyle_Santana_Resume.pdf)

**Comment by allysonaustin** [comment]
Thanks for submitting! I have a few edits and suggestions for you. 

Your skills section and brand statement seem awkwardly placed.  Keep the alignment consistent with the rest of the content and in a more intuitive space. It's less distracting for the reader. Additionally, you've got inconsistent spacing after each bold header - choose an appropriate amount of space and stick to it.

Include specific projects from DSI to strengthen your data science experience and showcase your skills. DSI should be listed as a line-item only in the education section, and a fully developed entry in the experience section.

No need to put two spaces after periods - just one is sufficient.

Nice work! Let me know if you have questions.
A
