### ISSUE TITLE
Christopher Messier Resume

### ISSUE THREAD

**Issue by messiest** [ga-dc-outcomes/deloitteresume#13]
Sorry this is late. I was working on it with Matt Brems.

[chris_messier-resume-deloitte.pdf](https://github.com/ga-dc-outcomes/deloitteresume/files/1423384/chris_messier-resume-deloitte.pdf)

**Comment by messiest** [comment]
I've been working on my resume all evening, and I hope it's not too late to submit some changes...

[chris_messier-resume-deloitte.pdf](https://github.com/ga-dc-outcomes/deloitteresume/files/1423827/chris_messier-resume-deloitte.pdf)

**Comment by allysonaustin** [comment]
Thanks for submitting! Your resume looks really clean - I have just one note for you.

In your DSI section, include the skills or programs you used to complete each of your projects; it makes this section much stronger by noting your proficiency with these skills.

Let me know if you have questions.
A
