### ISSUE TITLE
Ben Shaver Deloitte Resume

### ISSUE THREAD

**Issue by bpshaver** [ga-dc-outcomes/deloitteresume#14]
Here's a comment-able Google doc:

https://docs.google.com/document/d/1wPF67EvHfwJ48OgldDi2AdgEOMYpdjEsSARV5R6qmNU/edit?usp=sharing

The internet dying on Friday really put a damper on me finishing this sooner!

**Comment by allysonaustin** [comment]
Thanks for submitting! I've made comments on the document. Let me know if you have questions.
A
