### ISSUE TITLE
Alexander Holt Deloitte Resume

### ISSUE THREAD

**Issue by alexanderholt** [ga-dc-outcomes/deloitteresume#15]
[Alexander_Holt-Resume-Deloitte.pdf](https://github.com/ga-dc-outcomes/deloitteresume/files/1425805/Alexander_Holt-Resume-Deloitte.pdf)

**Comment by allysonaustin** [comment]
Thanks for submitting! Your resume looks really clean! I don't have any additional comments for you.

Let me know if you have questions.
A
