### ISSUE TITLE
Resume - Anirudh Kashyap - Deloitte

### ISSUE THREAD

**Issue by KashyapAndy** [ga-dc-outcomes/deloitteresume#2]
Hello,

Please find attached my updated resume for Deloitte.

[Resume - Anirudh Kashyap_New.docx](https://github.com/ga-dc-outcomes/deloitteresume/files/1419677/Resume.-.Anirudh.Kashyap_New.docx)

**Comment by CoachJoyhaugen** [comment]
Hi! 

I would encourage you to beef up your bullets. Add data and use different action verbs.  You say "Led" quite a bit.  Think "How many"  and "so what" with your bullets. 

You're on the right track

**Comment by KashyapAndy** [comment]
Updated Resume after receiving feedback from Allyson

[Resume - Anirudh Kashyap.pdf](https://github.com/ga-dc-outcomes/deloitteresume/files/1420562/Resume.-.Anirudh.Kashyap.pdf)
