### ISSUE TITLE
Wahl - Resume

### ISSUE THREAD

**Issue by dale-wahl** [ga-dc-outcomes/deloitteresume#3]
[Dale Wahl Resume brief.pdf](https://github.com/ga-dc-outcomes/deloitteresume/files/1420277/Dale.Wahl.Resume.brief.pdf)

**Comment by dale-wahl** [comment]
[Dale Wahl Resume brief.pdf](https://github.com/ga-dc-outcomes/deloitteresume/files/1422571/Dale.Wahl.Resume.brief.pdf)
 Last minute update.  I changed 'volunteer' to 'coordinator' for my PC experience.  Apparently that's what Peace Corps recommends.

**Comment by allysonaustin** [comment]
Great work, Dale! The only edit I have for you is to remove "our" from your So Others Might Eat section, since that position is past tense.

Nice job!
A
