### ISSUE TITLE
Joel Murphree DSI6 Deloitte Resume 

### ISSUE THREAD

**Issue by Joel-Murphree** [ga-dc-outcomes/deloitteresume#6]
[Joel.Murphree.Resume.11.17.docx](https://github.com/ga-dc-outcomes/deloitteresume/files/1422799/Joel.Murphree.Resume.11.17.docx)

**Comment by allysonaustin** [comment]
Thanks for submitting! I have just one quick comment for you.

Add your specific GA projects to your DSI section to strengthen it even more, and add a date to this entry so that its format is consistent with the rest of the resume. 

Let me know if you have questions.
A
