### ISSUE TITLE
Scott Vogel Deloitte resume

### ISSUE THREAD

**Issue by scottokinawa** [ga-dc-outcomes/deloitteresume#7]
[Scott Vogel's Resume .docx](https://github.com/ga-dc-outcomes/deloitteresume/files/1422886/Scott.Vogel.s.Resume.docx)

**Comment by allysonaustin** [comment]
Thanks for submitting! I have just a couple of quick comments for you.

Put spaces before the sets of parentheses in your skills section.

Fix the formatting on your graduation date for UC-Berkeley so it doesn't jump lines.

Is your Triage position still current? If it isn't, be sure to add an end date.

Great work! Let me know if you have questions.
A

**Comment by scottokinawa** [comment]
Hey Allyson,

When are these being submitted to Deloitte?

**Comment by allysonaustin** [comment]
My understanding is they'll be submitted sometime today, but I would check with Coach Joy to be sure!

A
